---
- name: Fact mas user
  set_fact:
    mas_user: '{{ mas_user | default(homebrew_user) | default(ansible_user_id) }}'
  tags:
    - mas

- become: '{{ (mas_user != ansible_user_id) | bool }}'
  become_user: '{{ mas_user }}'
  block:
    - name: Install required package
      ignore_errors: True
      homebrew:
        name: mas
        state: present
      tags:
        - mas

    - name: Check account status
      register: mas_account_result
      check_mode: False
      failed_when: mas_account_result.rc > 1
      changed_when: False
      command: /usr/local/bin/mas account
      tags:
        - mas

    - name: Write user script
      when:
        - mas_account_result.rc == 1
        - mas_email | default(False)
        - mas_password | default(False)
      template:
        src: signin.j2
        dest: '/Users/{{ mas_user }}/signin.scpt'
        owner: '{{ mas_user }}'
        group: staff
      tags:
        - mas

    - name: Execute user script
      when:
        - mas_account_result.rc == 1
        - mas_email | default(False)
        - mas_password | default(False)
      command: 'osascript /Users/{{ mas_user }}/signin.scpt'
      tags:
        - mas

    - name: Remove user script
      when:
        - mas_account_result.rc == 1
        - mas_email | default(False)
        - mas_password | default(False)
      file:
        path: '/Users/{{ mas_user }}/signin.scpt'
        state: absent
      tags:
        - mas

    - name: Gather installed apps
      register: mas_list_result
      check_mode: False
      changed_when: False
      command: /usr/local/bin/mas list
      tags:
        - mas

    - name: Remove defined apps
      loop: '{{ mas_remove_apps }}'
      when: (item.id | default(item) | string) in mas_list_result.stdout
      command: /usr/local/bin/mas uninstall "{{ item.id | default(item) }}"
      tags:
        - mas

    - name: Install defined apps
      loop: '{{ mas_install_apps }}'
      when: (item.id | default(item) | string) not in mas_list_result.stdout
      command: /usr/local/bin/mas install "{{ item.id | default(item) }}"
      tags:
        - mas

    - name: Upgrade installed apps
      when: mas_upgrade
      command: /usr/local/bin/mas upgrade
      tags:
        - mas

...
